// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `ClientBankInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.gjasinski.ds.slice;

public class OperationNotPermitted extends com.zeroc.Ice.UserException
{
    public OperationNotPermitted()
    {
    }

    public OperationNotPermitted(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::com::gjasinski::ds::slice::OperationNotPermitted";
    }

    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::com::gjasinski::ds::slice::OperationNotPermitted", -1, true);
        ostr_.endSlice();
    }

    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    public static final long serialVersionUID = -5477790306660186838L;
}
