// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ExchangeServiceInterface.proto

package com.gjasinski.ds.proto;

public interface CurrencyCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrencyCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  java.util.List<com.gjasinski.ds.proto.Currency> getCurrencyList();
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  int getCurrencyCount();
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  com.gjasinski.ds.proto.Currency getCurrency(int index);
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getCurrencyValueList();
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  int getCurrencyValue(int index);
}
