// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ExchangeServiceInterface.proto

package com.gjasinski.ds.proto;

public interface ExchangeStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExchangeStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Currency currency = 1;</code>
   */
  int getCurrencyValue();
  /**
   * <code>.Currency currency = 1;</code>
   */
  com.gjasinski.ds.proto.Currency getCurrency();

  /**
   * <code>double buy = 2;</code>
   */
  double getBuy();

  /**
   * <code>double sell = 3;</code>
   */
  double getSell();
}
